//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class banka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public banka()
        {
            this.klijent_racun = new HashSet<klijent_racun>();
        }
    
        public byte id_banka { get; set; }
        public string naziv { get; set; }
        public string skraceni { get; set; }
        public string prefiks { get; set; }
        public string broj_racuna { get; set; }
        public bool plata_spisak { get; set; }
        public string swift { get; set; }
        public string bankid { get; set; }
        public string adresa { get; set; }
        public string grad { get; set; }
        public Nullable<byte> id_drzava { get; set; }
    
        public virtual drzava drzava { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klijent_racun> klijent_racun { get; set; }
    }
}
