//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilans_stanja_view
    {
        public string Grupa { get; set; }
        public string naziv { get; set; }
        public string Redni_broj { get; set; }
        public Nullable<decimal> vrijednost { get; set; }
        public Nullable<decimal> Prethodna { get; set; }
        public int id_klijent { get; set; }
        public int godina { get; set; }
        public string Tip { get; set; }
    }
}
