//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dms_file
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dms_file()
        {
            this.dms_file1 = new HashSet<dms_file>();
            this.dms_file2 = new HashSet<dms_file>();
        }
    
        public int id_dms_file { get; set; }
        public int id_klijent { get; set; }
        public int id_tip { get; set; }
        public Nullable<int> id_operater { get; set; }
        public Nullable<int> id_knjiga { get; set; }
        public string id_revizija_scheme { get; set; }
        public string naziv { get; set; }
        public string extension { get; set; }
        public string guid { get; set; }
        public string guid_parent { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<bool> is_editable { get; set; }
        public string id_status { get; set; }
    
        public virtual dms_status dms_status { get; set; }
        public virtual dms_type dms_type { get; set; }
        public virtual klijent klijent { get; set; }
        public virtual knjiga knjiga { get; set; }
        public virtual operater operater { get; set; }
        public virtual revizija_scheme revizija_scheme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_file> dms_file1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_file> dms_file2 { get; set; }
    }
}
