//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class izvjestaj
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public izvjestaj()
        {
            this.izvjestaj_arhiva_dokument = new HashSet<izvjestaj_arhiva_dokument>();
            this.izvjestaj_dnevnik_def = new HashSet<izvjestaj_dnevnik_def>();
            this.izvjestaj_evidencija = new HashSet<izvjestaj_evidencija>();
            this.izvjestaj_prethodni = new HashSet<izvjestaj_prethodni>();
        }
    
        public string id_izvjestaj { get; set; }
        public string naziv { get; set; }
        public string report_name { get; set; }
        public string lang_naziv { get; set; }
        public Nullable<bool> aktivan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izvjestaj_arhiva_dokument> izvjestaj_arhiva_dokument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izvjestaj_dnevnik_def> izvjestaj_dnevnik_def { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izvjestaj_evidencija> izvjestaj_evidencija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izvjestaj_prethodni> izvjestaj_prethodni { get; set; }
    }
}
