//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class izvjestaj_arhiva_dokument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public izvjestaj_arhiva_dokument()
        {
            this.izvjestaj_arhiva_dnevnik = new HashSet<izvjestaj_arhiva_dnevnik>();
        }
    
        public int id_arhiva_dokument { get; set; }
        public int id_knjiga { get; set; }
        public string id_iskaz { get; set; }
        public Nullable<int> godina { get; set; }
    
        public virtual izvjestaj izvjestaj { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izvjestaj_arhiva_dnevnik> izvjestaj_arhiva_dnevnik { get; set; }
        public virtual knjiga knjiga { get; set; }
    }
}
