//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class klijent___djelatnost___sifra___opstina___drzava
    {
        public int ID_klijent { get; set; }
        public string Naziv { get; set; }
        public string Sifra { get; set; }
        public string Djelatnost { get; set; }
        public string Opstina { get; set; }
        public string Drzava { get; set; }
    }
}
