//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class klijent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klijent()
        {
            this.dms_file = new HashSet<dms_file>();
            this.izvjestaj_prethodni = new HashSet<izvjestaj_prethodni>();
            this.knjiga = new HashSet<knjiga>();
            this.klijent_racun = new HashSet<klijent_racun>();
            this.klijent_vlasnik = new HashSet<klijent_vlasnik>();
            this.klijent_zastupnik = new HashSet<klijent_zastupnik>();
            this.log = new HashSet<log>();
        }
    
        public int id_klijent { get; set; }
        public Nullable<int> id_tip { get; set; }
        public Nullable<short> id_opstina { get; set; }
        public Nullable<int> id_djelatnost { get; set; }
        public Nullable<int> id_velicina { get; set; }
        public Nullable<byte> id_drzava { get; set; }
        public string naziv { get; set; }
        public string adresa { get; set; }
        public string PIB { get; set; }
        public string pdv { get; set; }
        public string puni_naziv { get; set; }
        public string broj_rjesenja { get; set; }
        public Nullable<System.DateTime> datum_rjesenja { get; set; }
        public Nullable<System.DateTime> datum_gasenja { get; set; }
        public string grad { get; set; }
        public string mjesto { get; set; }
        public string telefon { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string posta_broj { get; set; }
        public string DMS_root { get; set; }
        public string direktor_ime { get; set; }
        public string direktor_JMBG { get; set; }
        public Nullable<System.DateTime> direktor_rodj { get; set; }
        public string direktor_otac { get; set; }
        public string direktor_majka { get; set; }
        public string direktor_majkaDjev { get; set; }
        public string direktor_brojlk { get; set; }
        public Nullable<byte> direktor_drzava_id { get; set; }
        public Nullable<short> direktor_opstina_id { get; set; }
        public string direktor_mjesto { get; set; }
        public string direktor_adresa { get; set; }
        public string direktor_ogranicenje { get; set; }
        public Nullable<bool> is_korisnik { get; set; }
        public Nullable<decimal> kapital_novac { get; set; }
        public Nullable<decimal> kapital_stvari { get; set; }
        public Nullable<decimal> kapital_prava { get; set; }
        public Nullable<int> id_revizor { get; set; }
        public Nullable<int> id_rukovodilac { get; set; }
        public Nullable<int> id_asistent { get; set; }
        public string erp_server { get; set; }
        public string erp_sqluser { get; set; }
        public string erp_sqlpass { get; set; }
        public string erp_dbname { get; set; }
    
        public virtual djelatnost djelatnost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dms_file> dms_file { get; set; }
        public virtual drzava drzava { get; set; }
        public virtual drzava drzava1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izvjestaj_prethodni> izvjestaj_prethodni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<knjiga> knjiga { get; set; }
        public virtual klijent_tip klijent_tip { get; set; }
        public virtual klijent_velicina klijent_velicina { get; set; }
        public virtual opstina opstina { get; set; }
        public virtual opstina opstina1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klijent_racun> klijent_racun { get; set; }
        public virtual revizorski_tim revizorski_tim { get; set; }
        public virtual revizorski_tim revizorski_tim1 { get; set; }
        public virtual revizorski_tim revizorski_tim2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klijent_vlasnik> klijent_vlasnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klijent_zastupnik> klijent_zastupnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log> log { get; set; }
    }
}
