//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class knjiga_dnevnik
    {
        public int id_knjiga_dnevnik { get; set; }
        public int id_knjiga { get; set; }
        public Nullable<int> broj_naloga { get; set; }
        public System.DateTime datum { get; set; }
        public string vrsta { get; set; }
        public string konto_broj { get; set; }
        public string konto_naziv { get; set; }
        public decimal duguje { get; set; }
        public decimal potrazuje { get; set; }
        public string opis { get; set; }
        public Nullable<int> sifra_partner { get; set; }
        public string naziv_partner { get; set; }
        public string sifra_rj { get; set; }
        public string naziv_rj { get; set; }
        public string konto_grupa { get; set; }
        public string konto_podgrupa { get; set; }
        public string konto_klasa { get; set; }
    
        public virtual knjiga knjiga { get; set; }
    }
}
