//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id_log { get; set; }
        public Nullable<int> id_operater { get; set; }
        public Nullable<int> id_klijent { get; set; }
        public System.DateTime datum { get; set; }
        public string tekst { get; set; }
        public string modul { get; set; }
    
        public virtual klijent klijent { get; set; }
        public virtual operater operater { get; set; }
    }
}
