//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database : DbContext
    {
    
        private RevizijaAPI.Klase.Configuration.ServerConnection Server { get; set; }
    
    	public Database()
            : this(RevizijaAPI.Klase.Configuration.Current.Connection)
        {
        }
        public Database(RevizijaAPI.Klase.Configuration.ServerConnection server)
            : base(server.GetConnection("*", "Models.Database.Model"))
        {
    		this.Server = server;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banka> banka { get; set; }
        public virtual DbSet<djelatnost> djelatnost { get; set; }
        public virtual DbSet<dms_file> dms_file { get; set; }
        public virtual DbSet<dms_status> dms_status { get; set; }
        public virtual DbSet<dms_type> dms_type { get; set; }
        public virtual DbSet<drzava> drzava { get; set; }
        public virtual DbSet<izvjestaj> izvjestaj { get; set; }
        public virtual DbSet<izvjestaj_arhiva_dnevnik> izvjestaj_arhiva_dnevnik { get; set; }
        public virtual DbSet<izvjestaj_arhiva_dokument> izvjestaj_arhiva_dokument { get; set; }
        public virtual DbSet<izvjestaj_dnevnik_def> izvjestaj_dnevnik_def { get; set; }
        public virtual DbSet<izvjestaj_evidencija> izvjestaj_evidencija { get; set; }
        public virtual DbSet<izvjestaj_pozicija> izvjestaj_pozicija { get; set; }
        public virtual DbSet<izvjestaj_prethodni> izvjestaj_prethodni { get; set; }
        public virtual DbSet<klijent> klijent { get; set; }
        public virtual DbSet<klijent_racun> klijent_racun { get; set; }
        public virtual DbSet<klijent_tip> klijent_tip { get; set; }
        public virtual DbSet<klijent_velicina> klijent_velicina { get; set; }
        public virtual DbSet<klijent_vlasnik> klijent_vlasnik { get; set; }
        public virtual DbSet<klijent_zastupnik> klijent_zastupnik { get; set; }
        public virtual DbSet<knjiga> knjiga { get; set; }
        public virtual DbSet<knjiga_dnevnik> knjiga_dnevnik { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<mailacc> mailacc { get; set; }
        public virtual DbSet<operater> operater { get; set; }
        public virtual DbSet<opstina> opstina { get; set; }
        public virtual DbSet<podesavanja> podesavanja { get; set; }
        public virtual DbSet<revizija_scheme> revizija_scheme { get; set; }
        public virtual DbSet<revizorski_tim> revizorski_tim { get; set; }
        public virtual DbSet<templates> templates { get; set; }
        public virtual DbSet<templates_type> templates_type { get; set; }
        public virtual DbSet<tim_funkcija> tim_funkcija { get; set; }
        public virtual DbSet<Bilans_stanja_view> Bilans_stanja_view { get; set; }
        public virtual DbSet<klijent___djelatnost___sifra___opstina___drzava> klijent___djelatnost___sifra___opstina___drzava { get; set; }
    }
}
