//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevizijaAPI.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class podesavanja
    {
        public int id_podesavanja { get; set; }
        public int id_operater { get; set; }
        public Nullable<bool> use_ftp { get; set; }
        public string dms_root { get; set; }
        public string dms_ftp_user { get; set; }
        public string dms_ftp_pass { get; set; }
        public string dms_ftp_server { get; set; }
    
        public virtual operater operater { get; set; }
    }
}
